import type { ServiceMeta, ServiceName } from "@/types";

export const SERVICES_META: Record<ServiceName, ServiceMeta> = {
  vercel: {
    name: "vercel",
    label: "Vercel",
    description: "Deploy et héberge ton app Next.js avec preview URLs automatiques.",
    category: "Infrastructure",
    logoUrl: "/logos/vercel.svg",
    color: "#ffffff",
    authType: "oauth",
    priority: 1,
    envVarNames: ["VERCEL_TOKEN", "VERCEL_PROJECT_ID", "VERCEL_ORG_ID"],
  },
  supabase: {
    name: "supabase",
    label: "Supabase",
    description: "Base de données PostgreSQL + Auth + Storage + Realtime.",
    category: "Database",
    logoUrl: "/logos/supabase.svg",
    color: "#3ecf8e",
    authType: "api_key",
    priority: 1,
    envVarNames: ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
  },
  stripe: {
    name: "stripe",
    label: "Stripe",
    description: "Paiements, abonnements et webhooks configurés automatiquement.",
    category: "Payments",
    logoUrl: "/logos/stripe.svg",
    color: "#635bff",
    authType: "oauth",
    priority: 1,
    envVarNames: ["STRIPE_SECRET_KEY", "STRIPE_PUBLISHABLE_KEY", "STRIPE_WEBHOOK_SECRET"],
  },
  resend: {
    name: "resend",
    label: "Resend",
    description: "Emails transactionnels avec API simple et analytics.",
    category: "Email",
    logoUrl: "/logos/resend.svg",
    color: "#000000",
    authType: "api_key",
    priority: 1,
    envVarNames: ["RESEND_API_KEY"],
  },
  github: {
    name: "github",
    label: "GitHub",
    description: "Crée le repo, pousse le boilerplate et connecte à Vercel.",
    category: "Infrastructure",
    logoUrl: "/logos/github.svg",
    color: "#ffffff",
    authType: "oauth",
    priority: 1,
    envVarNames: ["GITHUB_REPO_URL", "GITHUB_REPO_NAME"],
  },
  openai: {
    name: "openai",
    label: "OpenAI",
    description: "GPT-4o, DALL·E, Whisper — les APIs IA d'OpenAI.",
    category: "AI",
    logoUrl: "/logos/openai.svg",
    color: "#74aa9c",
    authType: "api_key",
    priority: 2,
    envVarNames: ["OPENAI_API_KEY"],
  },
  anthropic: {
    name: "anthropic",
    label: "Anthropic",
    description: "Claude Opus, Sonnet, Haiku — les LLM les plus intelligents.",
    category: "AI",
    logoUrl: "/logos/anthropic.svg",
    color: "#d4a96a",
    authType: "api_key",
    priority: 2,
    envVarNames: ["ANTHROPIC_API_KEY"],
  },
  elevenlabs: {
    name: "elevenlabs",
    label: "ElevenLabs",
    description: "Synthèse vocale ultra-réaliste en 30+ langues.",
    category: "AI",
    logoUrl: "/logos/elevenlabs.svg",
    color: "#f5a623",
    authType: "api_key",
    priority: 2,
    envVarNames: ["ELEVENLABS_API_KEY"],
  },
  clerk: {
    name: "clerk",
    label: "Clerk",
    description: "Auth complète : magic link, OAuth, MFA, orgs.",
    category: "Auth",
    logoUrl: "/logos/clerk.svg",
    color: "#6c47ff",
    authType: "api_key",
    priority: 2,
    envVarNames: ["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_SECRET_KEY"],
  },
  railway: {
    name: "railway",
    label: "Railway",
    description: "Deploy backend, workers et bases de données sans config.",
    category: "Infrastructure",
    logoUrl: "/logos/railway.svg",
    color: "#0b0d0e",
    authType: "api_key",
    priority: 2,
    envVarNames: ["RAILWAY_TOKEN"],
  },
  posthog: {
    name: "posthog",
    label: "PostHog",
    description: "Analytics produit, feature flags et replays de session.",
    category: "Analytics",
    logoUrl: "/logos/posthog.svg",
    color: "#f7a501",
    authType: "api_key",
    priority: 2,
    envVarNames: ["NEXT_PUBLIC_POSTHOG_KEY", "NEXT_PUBLIC_POSTHOG_HOST"],
  },
  upstash: {
    name: "upstash",
    label: "Upstash",
    description: "Redis serverless pour rate limiting, cache et queues.",
    category: "Cache",
    logoUrl: "/logos/upstash.svg",
    color: "#00e9a3",
    authType: "api_key",
    priority: 2,
    envVarNames: ["UPSTASH_REDIS_REST_URL", "UPSTASH_REDIS_REST_TOKEN"],
  },
  cloudflare: {
    name: "cloudflare",
    label: "Cloudflare",
    description: "CDN, DNS, Workers et protection DDoS.",
    category: "Infrastructure",
    logoUrl: "/logos/cloudflare.svg",
    color: "#f48120",
    authType: "api_key",
    priority: 2,
    envVarNames: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ZONE_ID"],
  },
};

export const PRIORITY_1_SERVICES: ServiceName[] = ["vercel", "supabase", "stripe", "resend", "github"];
export const PRIORITY_2_SERVICES: ServiceName[] = [
  "openai", "anthropic", "elevenlabs", "clerk", "railway", "posthog", "upstash", "cloudflare",
];

export const ALL_SERVICES = [...PRIORITY_1_SERVICES, ...PRIORITY_2_SERVICES];
