/**
 * GitHub integration — OAuth App
 * Docs: https://docs.github.com/en/rest
 */

const GITHUB_API = "https://api.github.com";

export interface GitHubRepo {
  id: number;
  name: string;
  full_name: string;
  html_url: string;
  clone_url: string;
}

export interface GitHubEnvVars extends Record<string, string> {
  GITHUB_REPO_URL: string;
  GITHUB_REPO_NAME: string;
  GITHUB_OWNER: string;
}

/** Exchange OAuth code for access token */
export async function exchangeCode(code: string): Promise<{ access_token: string; scope: string }> {
  const res = await fetch("https://github.com/login/oauth/access_token", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      client_id: process.env.GITHUB_CLIENT_ID!,
      client_secret: process.env.GITHUB_CLIENT_SECRET!,
      code,
      redirect_uri: `${process.env.NEXT_PUBLIC_APP_URL}/api/integrations/github/callback`,
    }),
  });

  if (!res.ok) throw new Error("GitHub OAuth exchange failed");

  const data = await res.json();
  if (data.error) throw new Error(`GitHub OAuth: ${data.error_description}`);

  return data;
}

/** Get the authenticated user */
export async function getUser(accessToken: string): Promise<{ login: string; id: number; name: string }> {
  const res = await fetch(`${GITHUB_API}/user`, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "User-Agent": "StackLaunch",
    },
  });

  if (!res.ok) throw new Error("Failed to fetch GitHub user");
  return res.json();
}

/** Create a new repository */
export async function createRepo(
  accessToken: string,
  name: string,
  isPrivate = true
): Promise<GitHubRepo> {
  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      "User-Agent": "StackLaunch",
    },
    body: JSON.stringify({
      name,
      private: isPrivate,
      auto_init: false,
      description: `Created by StackLaunch`,
    }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Failed to create GitHub repo: ${err.message ?? JSON.stringify(err)}`);
  }

  return res.json();
}

/** Push an initial README and .gitignore to bootstrap the repo */
export async function pushBoilerplate(
  accessToken: string,
  owner: string,
  repo: string,
  projectName: string
): Promise<void> {
  const files = [
    {
      path: "README.md",
      content: Buffer.from(
        `# ${projectName}\n\nCreated with [StackLaunch](https://stacklaunch.app).\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
      ).toString("base64"),
    },
    {
      path: ".gitignore",
      content: Buffer.from(
        `node_modules\n.env\n.env.local\n.next\ndist\n.DS_Store\n`
      ).toString("base64"),
    },
    {
      path: ".env.example",
      content: Buffer.from(
        `# Generated by StackLaunch — fill in your values\n# Run: npx stacklaunch pull to sync from StackLaunch\n`
      ).toString("base64"),
    },
  ];

  for (const file of files) {
    const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${file.path}`, {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
        "User-Agent": "StackLaunch",
      },
      body: JSON.stringify({
        message: `chore: init by StackLaunch`,
        content: file.content,
      }),
    });

    if (!res.ok) {
      const err = await res.json();
      throw new Error(`Failed to push ${file.path}: ${err.message}`);
    }
  }
}

/** Update .env.example in the repo with non-secret keys */
export async function updateEnvExample(
  accessToken: string,
  owner: string,
  repo: string,
  envVarKeys: string[]
): Promise<void> {
  // Get current file SHA
  const getRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/.env.example`, {
    headers: { Authorization: `Bearer ${accessToken}`, "User-Agent": "StackLaunch" },
  });

  const content = envVarKeys.map((k) => `${k}=`).join("\n") + "\n";

  const body: Record<string, string> = {
    message: "chore: update .env.example via StackLaunch",
    content: Buffer.from(content).toString("base64"),
  };

  if (getRes.ok) {
    const data = await getRes.json();
    body.sha = data.sha;
  }

  const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/.env.example`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      "User-Agent": "StackLaunch",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Failed to update .env.example: ${err.message}`);
  }
}

/** Returns env vars for this service */
export function getEnvVars(repoUrl: string, repoName: string, owner: string): GitHubEnvVars {
  return {
    GITHUB_REPO_URL: repoUrl,
    GITHUB_REPO_NAME: repoName,
    GITHUB_OWNER: owner,
  };
}

/** Build the OAuth redirect URL */
export function getOAuthUrl(state: string): string {
  const params = new URLSearchParams({
    client_id: process.env.GITHUB_CLIENT_ID!,
    redirect_uri: `${process.env.NEXT_PUBLIC_APP_URL}/api/integrations/github/callback`,
    scope: "repo,user",
    state,
  });
  return `https://github.com/login/oauth/authorize?${params}`;
}
